name: Pull Request
on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.PAT }}
          pr_label: "production"
          pr_title: "[Update] Update to main"
