
name: PR_creator


on:
  push:
    branches: 
      - staging
  pull_request:
    branches: 
      - staging

  workflow_dispatch:


jobs:
## create a pull request from staging to main everytime someone pushes to staging
  create_pr:
    name: create_pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create_pr
        uses: actions/create-pull-request@v1
        with:
          title: "PR from staging to main"
          head: staging
          base: main
          body: "This is a pull request from staging to main"
          labels:
            - staging
            - main
          draft: false
          maintainer_can_modify: true
          assignees:
            - "{{ github.actor }}"
          reviewers:
            - "{{ github.actor }}"
          milestone: "{{ github.pr.head.ref }}"
          repo: "{{ github.repository }}"
          token: "{{ github.token }}"