name: Pull Request
on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          source_branch: "staging"
          #github_token: ${{ secrets.PAT }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "production"
          pr_title: "[Update] Pulling ${{ github.ref }} into main"
          pr_reviewer: "td00,lavalaempchen"                         # Comma-separated list (no spaces)
          pr_assignee: "td00,lavalaempchen"
          pr_body: ":crown: *Update from staging to main*"                            
      - name: output-url
        run: echo ${{steps.open-pr.outputs.pr_url}}
      - name: output-number
        run: echo ${{steps.open-pr.outputs.pr_number}}
      - name: output-has-changed-files
        run: echo ${{steps.open-pr.outputs.has_changed_files}}